# Generated by Django 6.0.5 on 2026-05-11 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.DateTimeField()),
                ('total_testes', models.IntegerField()),
                ('testes_sucesso', models.IntegerField()),
                ('testes_falha', models.IntegerField()),
                ('tempo_execucao', models.FloatField()),
                ('cobertura_codigo', models.FloatField()),
                ('status', models.CharField(choices=[('SUCESSO', 'Sucesso'), ('FALHA', 'Falha'), ('PARCIAL', 'Parcial')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LogErro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='analytics.execucaoteste')),
            ],
        ),
    ]
